mvc/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Principal;
using System.Web;

namespace mvc.Models
{
    public class User
    {
        [Required]
        [Display(Name = "Login Name")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string firstname { get; set; }

        public string[] GetRoles(string loginId)
        {
            List<string> _return = new List<string>();
            string connSec = "Data Source=CRUS-ARIZONA.ou.ad3.ucdavis.edu;Initial Catalog=CRUS_Security;Integrated Security=True";
            // change this code to check for roles from the Security Database
            SqlConnection conn = new SqlConnection(connSec);
            using (conn)
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("GetUserRoles", conn);
                cmd.Parameters.Add(new SqlParameter("LoginId", System.Data.SqlDbType.VarChar)).Value = loginId;
                cmd.Parameters.Add(new SqlParameter("App", System.Data.SqlDbType.VarChar)).Value = "Permissions";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                SqlDataReader reader = cmd.ExecuteReader();
                while(reader.Read())
                {
                    _return.Add(reader[0].ToString());
                }
            }
            return _return.ToArray();
        }
    }

    public class CRUSIdentity : IIdentity
    {
        public string Name { get; set; }

        // Affiliation would be Faculty, Student or Staff (maybe Volunteer, External, Student Employee...)
        public string Affiliation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string HomeDepartment { get; set; }
        public string AuthenticationType
        {
            get { return "CRUS/CAS"; }
            set { throw new Exception("This attribute cannot be set."); }
        }
        public bool IsAuthenticated { get; set; }

        public CRUSIdentity(string UserName)
        {
            Name = UserName;

        }
    }

    public class CRUSPrincipal : IPrincipal
    {
        public IIdentity Identity { get; set; }

        public string[] Roles { get; set; }

        bool IPrincipal.IsInRole(string role)
        {
            throw new NotImplementedException();
        }
    }
}

mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Unauthorized()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

mvc/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Xml;

namespace mvc.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            string KerberosId = ""
               , Ticket = Request["ticket"]
               , Service = Request.Url.GetLeftPart(UriPartial.Path)
               ;

            // This is after they've logged into CAS, it would've redirected back here with
            // a ticket.
            if (Ticket != null)
            {
                string NetId = null;
                string ValidateUrl = "https://cas.ucdavis.edu/cas/serviceValidate?ticket=" + Ticket + "&service=" + Service;
                StreamReader Reader = new StreamReader(new WebClient().OpenRead(ValidateUrl));
                string Resp = Reader.ReadToEnd();
                NameTable NT = new NameTable();
                XmlNamespaceManager NSMgr = new XmlNamespaceManager(NT);
                XmlParserContext Context = new XmlParserContext(null, NSMgr, null, XmlSpace.None);
                XmlTextReader reader = new XmlTextReader(Resp, XmlNodeType.Element, Context);

                while (reader.Read())
                {
                    if (reader.IsStartElement())
                    {
                        string Tag = reader.LocalName;
                        if (Tag == "user")
                        {
                            NetId = reader.ReadString();
                        }
                    }
                }
                reader.Close();

                if (NetId != null)
                {
                    KerberosId = NetId;
                }
            } // End if Ticket is null.
            else
            {
                Session.Add("actionUrl", Request.RawUrl);
            }

            // If there was a ticket, it would've filled in the Kerberos ID.
            if (String.Equals(KerberosId, "") == false)
            {
                FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, KerberosId, DateTime.Now, DateTime.Now.AddMinutes(30), false, "App data for this user.", FormsAuthentication.FormsCookiePath);
                string encTicket = FormsAuthentication.Encrypt(ticket);
                Response.Cookies.Add(new System.Web.HttpCookie(FormsAuthentication.FormsCookieName, encTicket));
                try
                {
                    string[] sendTo = SplitUrl(Session["actionUrl"].ToString());
                    return RedirectToAction(sendTo[1], sendTo[0]);
                }
                catch
                {
                    FormsAuthentication.RedirectFromLoginPage(KerberosId, false);
                    return null;
                }
            }
            // This is when they first log into the page.
            else
            {
                string redir = "https://cas.ucdavis.edu/cas/" + "login?" + "service=" + Service;
                Response.Redirect(redir);
                return null;
            }
        }

        [HttpGet]
        public void Logout()
        {
            FormsAuthentication.SignOut();

            string redir = "https://cas.ucdavis.edu/cas/" + "logout?" + "service=" + Request.Url.GetLeftPart(UriPartial.Path);
            Response.Redirect(redir);
        }

        public string[] SplitUrl(string url)
        {
            //List<string> _return = new List<string>();

            //int _pos = url.IndexOf("%") + 3;
            //int _max = url.Length;
            //int _end = 0;
            //while (_pos < _max)
            //{
            //    _end = url.IndexOf("%", _pos);
            //    _return.Add(url.Substring(_pos, _end));
            //}

            return new string[] { "Home", "About" };
        }
    }
}

mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Test Project</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

mvc/Views/Home/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>That resource cannot be found.</h2>

mvc/Views/Home/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You are not authorized to view that resource.</h2>

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUS-IT Template", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@if (Request.IsAuthenticated)
                        {
                            @Html.ActionLink("Sign Out", "Logout", "User")
                        }
                        else
                        {
                            @Html.ActionLink("Sign In", "Login", "User")
                        }
                        </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Campus Recreation, Memorial Unions and UC Davis Stores &amp; UC Regents</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>